# Generated by Django 3.2.18 on 2023-03-01 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('loja', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('loja_id', models.IntegerField()),
                ('empresa', models.CharField(max_length=100)),
                ('parceiro', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('order_link', models.URLField()),
                ('integracao', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=50)),
                ('task_added_at', models.DateTimeField(auto_now_add=True)),
                ('is_solved', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
