# Generated by Django 3.2.18 on 2023-03-01 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_distribute', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
    ]
