# Generated by Django 3.2.18 on 2023-03-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_distribute', '0003_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
