# Generated by Django 3.2.18 on 2023-03-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_distribute', '0005_auto_20230302_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=None, max_length=155, null=True)),
                ('phone', models.CharField(blank=None, max_length=22, null=True)),
                ('tasks', models.ManyToManyField(blank=True, related_name='parceiro_tasks', to='app_distribute.Task')),
            ],
        ),
    ]
