# Generated by Django 3.2.18 on 2023-03-02 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_distribute', '0007_rename_parceiro_task_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parceiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_distribute.parceiro'),
        ),
    ]
