# Generated by Django 4.1.4 on 2023-03-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_distribute', '0010_task_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiro',
            name='email',
            field=models.EmailField(blank=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='phone',
            field=models.CharField(blank=None, max_length=33, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='empresa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='loja',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='origin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='partner',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
